-- Migration 002: Add design_document to ideas table
-- For storing detailed MVP descriptions with diagrams generated by AI

ALTER TABLE ideas ADD COLUMN IF NOT EXISTS design_document TEXT;

COMMENT ON COLUMN ideas.design_document IS 'AI-generated detailed design document with architecture diagrams (Mermaid syntax)';
